# A First workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: my first job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, world from ${{ github.actor}}"

      - name: checkout
        uses: actions/checkout@v4.1.0

      - run: tree /bin | wc -l
      - run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} From ${{ github.actor }}"
          echo "My secret is ${{ secrets.MY_SECRET }}"

jobs:
  second_job:
    name: my second_job job
    runs-on: ubuntu-latest
    steps:
      - run: echo "From second_job ---------"
      - run: hostname
jobs:
  third_job:
    name: my third_job job
    runs-on: ubuntu-latest
    steps:
      - run: echo "From third_job ------------"
      - run: hostname      

# On : [merge_group, push, pull_request, pull_request_target,  schedule, workflow_call, workflow_run, workflow_dispatch, branch_protection_rule, check_run, check_suite, commit_comment, create, delete, ] ... few more
